/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
export const RouterModuleNgFactory:i0.NgModuleFactory<i1.RouterModule> = i0.ɵcmf(i1.RouterModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.RouterModule,i1.RouterModule,[[2,i1.ɵa],[2,i1.Router]])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FwcGxlL1Byb2plY3RzL2JpcmRkZXNrLXNwYS1mcm9udGVuZC9ub2RlX21vZHVsZXMvQGFuZ3VsYXIvcm91dGVyL3JvdXRlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BcHBsZS9Qcm9qZWN0cy9iaXJkZGVzay1zcGEtZnJvbnRlbmQvbm9kZV9tb2R1bGVzL0Bhbmd1bGFyL3JvdXRlci9yb3V0ZXIuZC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OyJ9
