/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
export const CommonModuleNgFactory:i0.NgModuleFactory<i1.CommonModule> = i0.ɵcmf(i1.CommonModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i1.NgLocalization,i1.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i1.CommonModule,
          i1.CommonModule,([] as any[]))]);
    });
export const DeprecatedI18NPipesModuleNgFactory:i0.NgModuleFactory<i1.DeprecatedI18NPipesModule> = i0.ɵcmf(i1.DeprecatedI18NPipesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.DeprecatedI18NPipesModule,i1.DeprecatedI18NPipesModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FwcGxlL1Byb2plY3RzL2JpcmRkZXNrLXNwYS1mcm9udGVuZC9ub2RlX21vZHVsZXMvQGFuZ3VsYXIvY29tbW9uL2NvbW1vbi5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BcHBsZS9Qcm9qZWN0cy9iaXJkZGVzay1zcGEtZnJvbnRlbmQvbm9kZV9tb2R1bGVzL0Bhbmd1bGFyL2NvbW1vbi9jb21tb24uZC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
